In [ ]:
import pandas as pd

In [35]:
df = pd.read_csv("data/nyc_collision.csv")

C:\Users\harsh\AppData\Local\Temp\ipykernel_28612\2493743090.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/nyc_collision.csv")

In [36]:
df.head()

,:id,:version,:created_at,:updated_at,crash_date,crash_time,borough,zip_code,latitude,longitude,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
0,row-rsc3.wgwr-zpi9,rv-qukg_54rg~e45q,2021-09-14T22:52:22.882Z,2021-09-14T22:52:26.672Z,2021-09-11T00:00:00.000,2:39,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4455765,Sedan,Sedan,NaN,NaN,NaN
1,row-t9dc~q8a7~jwk4,rv-vmia.j6tc.thwm,2022-03-29T22:52:48.720Z,2022-03-29T22:52:49.994Z,2022-03-26T00:00:00.000,11:45,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4513547,Sedan,NaN,NaN,NaN,NaN
2,row-h8ny_qxbv_ezwp,rv-x4h8~yx6x.vdk4,2023-11-06T23:52:10.201Z,2023-11-06T23:52:18.104Z,2023-11-01T00:00:00.000,1:29,BROOKLYN,11230.0,40.62179,-73.970024,...,Unspecified,Unspecified,NaN,NaN,4675373,Moped,Sedan,Sedan,NaN,NaN
3,row-gxrs-hm78-w9gs,rv-fazg.rwsa.9gjd,2022-07-04T22:51:56.069Z,2022-07-04T22:52:04.895Z,2022-06-29T00:00:00.000,6:55,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4541903,Sedan,Pick-up Truck,NaN,NaN,NaN
4,row-58i4.zk9q.sxqs,rv-4bks~69au~m7kz,2022-09-26T22:52:05.596Z,2022-09-26T22:52:11.092Z,2022-09-21T00:00:00.000,13:21,NaN,NaN,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4566131,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,NaN

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2220334 entries, 0 to 2220333
Data columns (total 33 columns):
 #   Column                         Dtype
---  ------                         -----
 0   :id                            object
 1   :version                       object
 2   :created_at                    object
 3   :updated_at                    object
 4   crash_date                     object
 5   crash_time                     object
 6   borough                        object
 7   zip_code                       object
 8   latitude                       float64
 9   longitude                      float64
 10  location                       object
 11  on_street_name                 object
 12  off_street_name                object
 13  cross_street_name              object
 14  number_of_persons_injured      float64
 15  number_of_persons_killed       float64
 16  number_of_pedestrians_injured  int64
 17  number_of_pedestrians_killed   int64
 18  number_of_cyclist_injured      int64
 19  number_of_cyclist_killed       int64
 20  number_of_motorist_injured     int64
 21  number_of_motorist_killed      int64
 22  contributing_factor_vehicle_1  object
 23  contributing_factor_vehicle_2  object
 24  contributing_factor_vehicle_3  object
 25  contributing_factor_vehicle_4  object
 26  contributing_factor_vehicle_5  object
 27  collision_id                   int64
 28  vehicle_type_code1             object
 29  vehicle_type_code2             object
 30  vehicle_type_code_3            object
 31  vehicle_type_code_4            object
 32  vehicle_type_code_5            object
dtypes: float64(4), int64(7), object(22)
memory usage: 559.0+ MB

In [38]:
df['crash_date'] = pd.to_datetime(df['crash_date'], errors='coerce')
df['crash_time'] = pd.to_datetime(df['crash_time'], format='%H:%M', errors='coerce')

In [48]:
distinct_boroughs = df['borough'].unique()
print(distinct_boroughs)

['BROOKLYN' 'BRONX' 'MANHATTAN' 'QUEENS' 'STATEN ISLAND']

In [39]:
df = df.dropna(subset=['borough', 'latitude', 'longitude'])

In [40]:
df.head()

,:id,:version,:created_at,:updated_at,crash_date,crash_time,borough,zip_code,latitude,longitude,...,contributing_factor_vehicle_2,contributing_factor_vehicle_3,contributing_factor_vehicle_4,contributing_factor_vehicle_5,collision_id,vehicle_type_code1,vehicle_type_code2,vehicle_type_code_3,vehicle_type_code_4,vehicle_type_code_5
2,row-h8ny_qxbv_ezwp,rv-x4h8~yx6x.vdk4,2023-11-06T23:52:10.201Z,2023-11-06T23:52:18.104Z,2023-11-01,1900-01-01 01:29:00,BROOKLYN,11230.0,40.621790,-73.970024,...,Unspecified,Unspecified,NaN,NaN,4675373,Moped,Sedan,Sedan,NaN,NaN
9,row-ih2j-xch6_fenf,rv-e9zc.xr5k-68h5,2021-09-14T22:52:22.882Z,2021-09-14T22:52:26.672Z,2021-09-11,1900-01-01 09:35:00,BROOKLYN,11208.0,40.667202,-73.866500,...,NaN,NaN,NaN,NaN,4456314,Sedan,NaN,NaN,NaN,NaN
10,row-qe7r_he2n~zchc,rv-vpwg.k5qh.zhc9,2021-12-17T23:52:47.817Z,2021-12-17T23:52:52.600Z,2021-12-14,1900-01-01 08:13:00,BROOKLYN,11233.0,40.683304,-73.917274,...,NaN,NaN,NaN,NaN,4486609,NaN,NaN,NaN,NaN,NaN
13,row-hpfw.kfmw_56zk,rv-m9du-h9pt~83rq,2021-12-17T23:52:47.817Z,2021-12-17T23:52:52.600Z,2021-12-14,1900-01-01 08:17:00,BRONX,10475.0,40.868160,-73.831480,...,Unspecified,NaN,NaN,NaN,4486660,Sedan,Sedan,NaN,NaN,NaN
14,row-mf46.qqxh.jwhb,rv-fjns_aj3x-6vnq,2021-12-17T23:52:47.817Z,2021-12-17T23:52:52.600Z,2021-12-14,1900-01-01 21:10:00,BROOKLYN,11207.0,40.671720,-73.897100,...,Unspecified,NaN,NaN,NaN,4487074,Sedan,NaN,NaN,NaN,NaN

In [49]:
distinct_boroughs = df['borough'].unique()
print(distinct_boroughs)

['BROOKLYN' 'BRONX' 'MANHATTAN' 'QUEENS' 'STATEN ISLAND']

In [41]:
df['hour'] = df['crash_time'].dt.hour

In [42]:
def time_of_day(h):
    if 5 <= h < 12:
        return 'Morning'
    elif 12 <= h < 17:
        return 'Afternoon'
    elif 17 <= h < 21:
        return 'Evening'
    else:
        return 'Night'

In [43]:
df['time_of_day'] = df['hour'].apply(time_of_day)

In [44]:
ped = df[df['number_of_pedestrians_injured'] + df['number_of_pedestrians_killed'] > 0]
cyc = df[df['number_of_cyclist_injured'] + df['number_of_cyclist_killed'] > 0]

In [46]:
df.to_csv("data/cleaned_collision_data.csv", index=False)
ped.to_csv("data/pedestrian_collisions.csv", index=False)
cyc.to_csv("data/cyclist_collisions.csv", index=False)